### ISSUE TITLE
MasterDB Close by multi sync

### ISSUE THREAD

**Issue by tnug384** [Angelelz/KeePassMasterSlaveSync#6]
Hello,

as long as the slave entry is enabled the master DB is closed, when I sync it with an copy in an other path via Trigger "Synchronize active db with file/url"

As soon as I disable the entry the master DB stays open. 

Any idea

kind regards

**Comment by Angelelz** [comment]
Remember this plugin is executed every time you save the database. Whether is saved by a trigger or another plugin.
Anyway, I didn't really understand your problem, is the master DB being closed by the plugin? Could you elaborate a little more so I can reproduce? How is the trigger set?

**Comment by holygoatnickels** [comment]
I believe I am experiencing the same issue that tnug384 is having.

For testing I downloaded a portable version of keepass and launched it from scratch without any customization except your plugin.  I open my Master DB fine, but when I press save it closes the master DB and then reopens.

this happens so fast, and the only reason I would have noticed is my DB is set to warn me if my master password is over 90 days old, and that pops up each time after saving.

Let me know if this clarifies or if you need more information.

**Comment by FFW-BHH** [comment]
I also have the same problem => I have a master DB open that should synchronize some folders with other slave DBs.
If I change something in the master DB and save the changes the sync job starts and closes the master DB and reopens an empty KeePass session - no DB is already open then.
Because of that I am not able to access my standard KeePass DB from the minimized tray during the sync jobs of the plugin are configured / online.

If I set the sync jobs to "expired" everything works as expected again => after saving changes in the master DB KeePass minimizes to tray with the locked master DB and I am able to work with it the normal way (e.g. for using auto-type).

Does anybody know a solution for that?

**Comment by Angelelz** [comment]
I'm going to look into this further. I use the plugin on a daily basis and always get de masterDB to open right after the sync job.

**Comment by Elvagor** [comment]
Any news on this issue? I seem to be subject to it too: I have set up a Master and a Slave, with a Sync job from Master to Slave. Each time I save the Master, the sync job is performed correctly, but both Master and Slave get closed and the KeePass window remains empty. Is there a way to avoid to close at least the Master? Thanks!

Edit: I'm also using the Google Sync Plugin on the Master, and it seems like the combination of the two plugins is causing my issue. Disabling either one makes the issue disappear.

**Comment by nilshoell** [comment]
I can also reproduce this problem, although it seems to be slightly different.

As with the others, I have a KeePass trigger that executes on saving the DB to synchronise it with another DB remotely.
If I save my main (master) DB, it gets closed and reopened at least for a moment, since KeeAutoExec triggers to open some other DBs unaffected by the Master/Slave sync.

I still have the tab with my master DB visible in KeePass, but the programm crashes when I click it:

```
System.ArgumentException: The value is outside the expected range.
   at KeePass.UI.DocumentManagerEx.set_ActiveDocument(PwDocument value)
   at KeePass.Forms.MainForm.UpdateUI(Boolean bRecreateTabBar, PwDocument dsSelect, Boolean bUpdateGroupList, PwGroup pgSelect, Boolean bUpdateEntryList, PwGroup pgEntrySource, Boolean bSetModified, Control cOptFocus)
   at KeePass.Forms.MainForm.MakeDocumentActive(PwDocument ds)
   at KeePass.Forms.MainForm.OnTabMainSelectedIndexChanged(Object sender, EventArgs e)
   at System.Windows.Forms.TabControl.OnSelectedIndexChanged(EventArgs e)
   at System.Windows.Forms.TabControl.WmSelChange()
   at System.Windows.Forms.TabControl.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
  ```

It seems like the reopening of the DB goes wrong, maybe because the synchronisation has not completed.  
I use the officially recommended way for synchronising with triggers without any plugins, as described here: https://keepass.info/help/kb/trigger_examples.html#dbsync

**Edit:**\
If I disable the sync job by setting the "Expire" property, the DB also seems to close and reopen one more time after saving, without any crashes. The only thing changing here is the Master/Slave sync, the other synchronisation using triggers is still active.

**Comment by jasonc-glitch** [comment]
I believe I am having this issue.  In my case I have some triggers enabled that do an automatic save on the master database after a set idle time.  When these are enabled, if I do a manual save on the master it does a synchronisation to the slave database OK but it closes the master database and I'm left with Keepass running but no database open.

When I disable the trigger system and do the same save, it works fine (ie. synchronisation runs and the Master Database is left open).
